---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: certificate-manager-opnsense
  namespace: networking
spec:
  schedule: "1 1 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cert-manager-opnsense
            image: ghcr.io/tobiass1402/cert-manager-opnsense:main
            imagePullPolicy: Always
            env:
              - name: OPNSENSE_HOST
                value: 
              - name: API_KEY
                value: 
              - name: API_SECRET
                value: 
              - name: CERT_UUID
                value: 
              - name: CA_UUID
                value: 
              - name: SECRET_NAME
                value: intranet
          restartPolicy: OnFailure
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: networking
  name: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-binding
  namespace: networking
subjects:
- kind: ServiceAccount
  name: default
  namespace: networking
roleRef:
  kind: Role
  name: cert-manager
  apiGroup: rbac.authorization.k8s.io
