apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-binding
  namespace: networking
subjects:
- kind: ServiceAccount
  name: default
  namespace: networking
roleRef:
  kind: Role
  name: cert-manager
  apiGroup: rbac.authorization.k8s.io